[package]
name = "bonding-curve-contract-meta"
version = "0.0.0"
authors = ["Alin Cruceat <alin.cruceat@dharithri.com>"]
edition = "2021"
publish = false

[dependencies.bonding-curve-contract]
path = ".."

[dependencies.dharithri-sc-meta]
version = "0.43.3"
path = "../../../../framework/meta"
