[package]
name = "transfer-role-features"
version = "0.0.0"
authors = ["Dorin Marian Iancu <dorin.iancu@dharithri.com>"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dev-dependencies.vault]
path = "../vault"

[dependencies.dharithri-sc]
version = "0.43.3"
path = "../../../../framework/base"

[dependencies.dharithri-sc-modules]
version = "0.43.3"
path = "../../../../contracts/modules"

[dev-dependencies.dharithri-sc-scenario]
version = "0.43.3"
path = "../../../../framework/scenario"
