// Code generated by the dharithri-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            2
// Async Callback (empty):               1
// Total number of exported functions:   4

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

dharithri_sc_wasm_adapter::allocator!();
dharithri_sc_wasm_adapter::panic_handler_with_message!();

dharithri_sc_wasm_adapter::endpoints! {
    panic_message_features
    (
        init => init
        panicWithMessage => panic_with_message
        panicAfterLog => panic_after_log
    )
}

dharithri_sc_wasm_adapter::async_callback_empty! {}
