// Code generated by the dharithri-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

dharithri_sc_wasm_adapter::allocator!();
dharithri_sc_wasm_adapter::panic_handler!();

dharithri_sc_wasm_adapter::endpoints! {
    digital_cash
    (
        init => init
        fund => fund
        withdraw => withdraw
        claim => claim
        claimFees => claim_fees
        depositFees => deposit_fees
        forward => forward
        getAmount => get_amount
        deposit => deposit
    )
}

dharithri_sc_wasm_adapter::async_callback_empty! {}
