[package]
name = "forwarder-queue"
version = "0.0.0"
authors = ["Costin Carabas <costin.carabas@dharithri.com>"]
edition = "2021"
publish = false

[lib]
path = "src/forwarder_queue.rs"

[features]
promises = ["dharithri-sc/promises"]

[dependencies.vault]
path = "../vault"

[dependencies.dharithri-sc]
version = "0.43.3"
path = "../../../../framework/base"

[dependencies.dharithri-sc-wasm-adapter]
version = "0.43.3"
path = "../../../../framework/wasm-adapter"
optional = true

[dev-dependencies.dharithri-sc-scenario]
version = "0.43.3"
path = "../../../../framework/scenario"
