[package]
name = "basic-features-interact"
version = "0.0.0"
authors = ["Ovidiu Stinga <ovidiu.stinga@dharithri.com>"]
edition = "2021"
publish = false

[[bin]]
name = "basic-features-interact"
path = "src/bf_interact.rs"

[dependencies]
clap = { version = "4.1.0", features = ["derive", "cargo"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.7.2"

[dependencies.basic-features]
path = ".."

[dependencies.dharithri-sc-snippets]
version = "0.43.3"
path = "../../../../framework/snippets"
