[package]
name = "second-contract-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.second-contract]
path = ".."

[dependencies.dharithri-sc]
version = "0.43.3"
path = "../../../../../../framework/base"

[dependencies.dharithri-sc-meta]
version = "0.43.3"
path = "../../../../../../framework/meta"
