[package]
name = "fractional-nfts-meta"
version = "0.0.0"
authors = ["kasi <contact@dharithri.org>"]
edition = "2021"
publish = false

[dependencies.fractional-nfts]
path = ".."

[dependencies.dharithri-sc-meta]
version = "0.43.3"
path = "../../../../framework/meta"
