// Code generated by the dharithri-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

dharithri_sc_wasm_adapter::allocator!();
dharithri_sc_wasm_adapter::panic_handler!();

dharithri_sc_wasm_adapter::endpoints! {
    esdt_transfer_with_fee
    (
        init => init
        setExactValueFee => set_exact_value_fee
        setPercentageFee => set_percentage_fee
        claimFees => claim_fees
        transfer => transfer
        getTokenFee => token_fee
        getPaidFees => paid_fees
    )
}

dharithri_sc_wasm_adapter::async_callback_empty! {}
