[package]
name = "single-value-repeat"
version = "0.0.0"
authors = ["kasi <contact@dharithri.org>"]
edition = "2021"
publish = false

[lib]
path = "src/single_value_repeat.rs"

[dependencies.benchmark-common]
path = "../benchmark-common"


[dependencies.dharithri-sc]
version = "0.43.3"
path = "../../../../framework/base"

[dev-dependencies.dharithri-sc-scenario]
version = "0.43.3"
path = "../../../../framework/scenario"
