// Code generated by the dharithri-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            4
// Async Callback (empty):               1
// Total number of exported functions:   6

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

dharithri_sc_wasm_adapter::allocator!();
dharithri_sc_wasm_adapter::panic_handler!();

dharithri_sc_wasm_adapter::endpoints! {
    parent
    (
        init => init
        deposit => deposit
        deployChildContract => deploy_child_contract
        executeOnDestIssueToken => execute_on_dest_issue_token
        getChildContractAddress => child_contract_address
    )
}

dharithri_sc_wasm_adapter::async_callback_empty! {}
