[package]
name = "kitty-genetic-alg"
version = "0.0.0"
authors = [ "dorin-iancu <dorin.iancu@dharithri.com>",]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"


[dependencies.kitty]
version = "0.0.0"
path = "../common/kitty"

[dependencies.random]
version = "0.0.0"
path = "../common/random"

[dependencies.dharithri-sc]
version = "0.43.3"
path = "../../../../framework/base"

[dev-dependencies.dharithri-sc-scenario]
version = "0.43.3"
path = "../../../../framework/scenario"
