[package]
name = "esdt-system-sc-mock-meta"
version = "0.0.0"
authors = ["Dorin Marian Iancu <dorin.iancu@dharithri.com>"]
edition = "2021"
publish = false

[dependencies.esdt-system-sc-mock]
path = ".."

[dependencies.dharithri-sc-meta]
version = "0.43.3"
path = "../../../../framework/meta"
