[package]
name = "rewards-distribution-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["kasi <contact@dharithri.org>"]

[dev-dependencies]

[dependencies.rewards-distribution]
path = ".."

[dependencies.dharithri-sc-meta]
version = "0.43.3"
path = "../../../../framework/meta"
