[package]
name = "dharithri-price-aggregator-sc-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.dharithri-price-aggregator-sc]
path = ".."

[dependencies.dharithri-sc]
version = "0.43.3"
path = "../../../../framework/base"

[dependencies.dharithri-sc-meta]
version = "0.43.3"
path = "../../../../framework/meta"
