[package]
name = "kitty"
version = "0.0.0"
authors = [ "dorin-iancu <dorin.iancu@dharithri.com>",]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.dharithri-sc]
version = "0.43.3"
path = "../../../../../framework/base"

[dependencies.random]
version = "0.0.0"
path = "../random"
