[package]
name = "crowdfunding-erc20"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@dharithri.com>"]
edition = "2021"
publish = false

[lib]
path = "src/crowdfunding_erc20.rs"

[dependencies.erc20]
path = "../erc20"

[dependencies.dharithri-sc]
version = "0.43.3"
path = "../../../../framework/base"

[dev-dependencies.dharithri-sc-scenario]
version = "0.43.3"
path = "../../../../framework/scenario"

