[package]
name = "esdt-contract-pair"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@dharithri.com>"]
edition = "2021"
publish = false

[dev-dependencies.first-contract]
path = "first-contract"

[dev-dependencies.second-contract]
path = "second-contract"

[dev-dependencies.dharithri-sc]
version = "0.43.3"
path = "../../../../framework/base"

[dev-dependencies.dharithri-sc-scenario]
version = "0.43.3"
path = "../../../../framework/scenario"
