// Code generated by the dharithri-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

dharithri_sc_wasm_adapter::allocator!();
dharithri_sc_wasm_adapter::panic_handler!();

dharithri_sc_wasm_adapter::endpoints! {
    crypto_bubbles
    (
        init => init
        topUp => top_up
        withdraw => withdraw
        joinGame => join_game
        rewardWinner => reward_winner
        rewardAndSendToWallet => reward_and_send_to_wallet
        balanceOf => player_balance
    )
}

dharithri_sc_wasm_adapter::async_callback_empty! {}
