[package]
name = "dharithri-price-aggregator-sc-wasm"
version = "0.0.0"
authors = [ "kasi <contact@dharithri.org>",]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"

[dependencies.dharithri-price-aggregator-sc]
path = ".."

[dependencies.dharithri-sc-wasm-adapter]
version = "0.43.3"
path = "../../../../framework/wasm-adapter"

[workspace]
members = ["."]
