[package]
name = "big-float-features-meta"
version = "0.0.0"
authors = ["viswanath <contact@dharithri.org>"]
edition = "2021"
publish = false

[dependencies.big-float-features]
path = ".."

[dependencies.dharithri-sc-meta]
version = "0.43.3"
path = "../../../../framework/meta"
