[package]
name = "multisig-interact"
version = "0.0.0"
authors = ["viswanath <contact@dharithri.org>"]
edition = "2021"
publish = false

[[bin]]
name = "multisig-interact"
path = "src/multisig_interact.rs"

[dependencies]
clap = { version = "4.1.0", features = ["derive", "cargo"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.7.2"

[dependencies.multisig]
path = ".."

[dependencies.dharithri-sc-modules]
version = "0.43.3"
path = "../../../../contracts/modules"

[dependencies.dharithri-sc-snippets]
version = "0.43.3"
path = "../../../../framework/snippets"

[dependencies.dharithri-sc-scenario]
version = "=0.43.3"
path = "../../../../framework/scenario"
