[package]
name = "linked-list-repeat-meta"
version = "0.0.0"
authors = ["viswanath <contact@dharithri.org>"]
edition = "2021"
publish = false

[dependencies.linked-list-repeat]
path = ".."

[dependencies.dharithri-sc-meta]
version = "0.43.3"
path = "../../../../../framework/meta"
