// Code generated by the dharithri-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            7
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

dharithri_sc_wasm_adapter::allocator!();
dharithri_sc_wasm_adapter::panic_handler!();

dharithri_sc_wasm_adapter::endpoints! {
    dharithri_wegld_swap_sc
    (
        init => init
        wrapEgld => wrap_egld
        unwrapEgld => unwrap_egld
        getLockedEgldBalance => get_locked_egld_balance
        getWrappedEgldTokenId => wrapped_egld_token_id
        pause => pause_endpoint
        unpause => unpause_endpoint
        isPaused => paused_status
    )
}

dharithri_sc_wasm_adapter::async_callback_empty! {}
